### ISSUE TITLE
Cannot find module 'graphql'

### ISSUE THREAD

**Issue by JamesSingleton** [loic-carbonne/realtime-notifications-apollo-graphql#1]
I think we the latest versions of apollo-server-express, this breaks. I put the code in that you have for the backend index.js and do `node index.js` and I get the following error:
```
module.js:529
    throw err;
    ^

Error: Cannot find module 'graphql'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Coding\SandBox\GraphQL\real-time-notification-backend\node_modules\apollo-server-core\dist\runQuery.js:3:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by JamesSingleton** [comment]
If anyone finds this in the future... install `graphql` as a dependency. Not sure what has changed in the few months that you have to independently install this, but you do.
